# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('transaction_code', models.CharField(max_length=36)),
                ('payment_method', models.CharField(choices=[('card', '\uc2e0\uc6a9\uce74\ub4dc')], default='card', max_length=20)),
                ('payment_status', models.CharField(max_length=10)),
                ('payment_message', models.CharField(max_length=255, null=True)),
                ('vbank_num', models.CharField(blank=True, max_length=255, null=True)),
                ('vbank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('vbank_date', models.CharField(blank=True, max_length=50, null=True)),
                ('vbank_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
