# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160323_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='has_additional_price',
            field=models.BooleanField(default=False),
        ),
    ]
