# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_option_has_additional_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='additional_price',
            field=models.IntegerField(default=0),
        ),
    ]
