# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_additional_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='total',
            field=models.IntegerField(default=500),
        ),
    ]
