# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_option_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('bank', 'Bank Transfer')], default='card', max_length=20),
        ),
    ]
