# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160416_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
