# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20160418_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('paid', 'Paid'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], default='ready', max_length=10),
        ),
    ]
