# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20160501_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('bank', 'Bank Transfer'), ('vbank', 'Virtual Bank Transfer')], default='card', max_length=20),
        ),
    ]
