# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20170428_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('vbank', 'Virtual Bank Transfer')], default='card', max_length=20),
        ),
    ]
