# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170515_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='top_size',
            field=models.CharField(choices=[('small', 'S(85)'), ('medium', 'M(90)'), ('large', 'L(95)'), ('xlarge', 'XL(100)'), ('2xlarge', '2XL(105)'), ('3xlarge', '3XL(110)'), ('4xlarge', '3XL(115)')], default='L', max_length=20),
        ),
    ]
