# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20170630_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['price']},
        ),
    ]
