# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20170701_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='cancelable_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='is_cancelable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='top_size',
            field=models.CharField(blank=True, choices=[('small', 'S(85)'), ('medium', 'M(90)'), ('large', 'L(95)'), ('xlarge', 'XL(100)'), ('2xlarge', '2XL(105)'), ('3xlarge', '3XL(110)'), ('4xlarge', '3XL(115)')], default=None, max_length=20, null=True),
        ),
    ]
