# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20170701_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='cancelable_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='is_cancelable',
            field=models.BooleanField(default=False),
        ),
    ]
