# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0021_auto_20170713_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('merchant_uid', models.CharField(blank=True, db_index=True, max_length=32)),
                ('imp_uid', models.CharField(blank=True, max_length=32, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=36)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card')], default='card', max_length=20)),
                ('payment_status', models.CharField(choices=[('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='ready', max_length=10)),
                ('payment_message', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
