# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0023_auto_20170722_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issued', models.BooleanField(default=False)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('reissue_date', models.DateTimeField(blank=True, null=True)),
                ('reissue_count', models.IntegerField(default=0)),
                ('issue_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='count_reissue',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='issue_ticket',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reissue_date',
        ),
        migrations.AddField(
            model_name='issueticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Registration'),
        ),
    ]
