# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20170723_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueticket',
            old_name='issue_manager',
            new_name='issuer',
        ),
        migrations.RenameField(
            model_name='issueticket',
            old_name='user',
            new_name='registration',
        ),
        migrations.RemoveField(
            model_name='issueticket',
            name='is_issued',
        ),
        migrations.RemoveField(
            model_name='issueticket',
            name='reissue_count',
        ),
        migrations.RemoveField(
            model_name='issueticket',
            name='reissue_date',
        ),
        migrations.AlterField(
            model_name='issueticket',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
