# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='language',
            field=models.CharField(choices=[(b'E', 'English'), (b'K', 'Korean')], default=b'E', max_length=1),
        ),
    ]
