# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0002_proposal_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
