# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0005_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='difficulty',
            field=models.CharField(choices=[(b'B', 'Beginner'), (b'I', 'Intermediate'), (b'E', 'Experienced')], default=b'B', max_length=1),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(choices=[(b'S', '25 mins'), (b'L', '40 mins')], default=b'S', max_length=1),
        ),
        migrations.AddField(
            model_name='speaker',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(choices=[(b'E', 'English'), (b'K', 'Korean')], default=b'E', max_length=1),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_ko',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
