# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyconkr', '0006_matching_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField(max_length=1000)),
                ('desc', models.TextField(max_length=4000)),
                ('comment', models.TextField(blank=True, max_length=4000, null=True)),
                ('difficulty', models.CharField(choices=[(b'B', 'Beginner'), (b'I', 'Intermediate'), (b'E', 'Experienced')], max_length=1)),
                ('duration', models.CharField(choices=[(b'S', '1 hour'), (b'M', '2 hours'), (b'L', '4 hours')], max_length=1)),
                ('language', models.CharField(choices=[(b'E', 'English'), (b'K', 'Korean')], default=b'E', max_length=1)),
                ('capacity', models.CharField(choices=[(b'S', '10 people'), (b'M', '45 people'), (b'L', '100 people')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
