# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0007_auto_20160625_1618'),
        ('pyconkr', '0007_tutorialproposal'),
    ]

    operations = [
    ]
