# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0009_auto_20160630_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialproposal',
            name='type',
            field=models.CharField(choices=[(b'T', 'Tutorial'), (b'S', 'Sprint')], default=b'T', max_length=1),
        ),
    ]
