# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0011_auto_20160719_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialproposal',
            name='desc',
            field=models.TextField(),
        ),
    ]
