# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0014_auto_20170630_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sprintcheckin',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sprintcheckin',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='sprintcheckin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sprintproposal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='type',
            field=models.CharField(choices=[('T', 'Tutorial'), ('S', 'Sprint')], default='T', max_length=1),
        ),
        migrations.DeleteModel(
            name='SprintCheckin',
        ),
        migrations.DeleteModel(
            name='SprintProposal',
        ),
    ]
