# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyconkr', '0015_auto_20170630_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintCheckin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SprintProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('project_url', models.CharField(max_length=1024)),
                ('project_brief', models.TextField(max_length=1000)),
                ('contribution_desc', models.TextField()),
                ('comment', models.TextField(blank=True, max_length=4000, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='type',
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprintcheckin',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyconkr.SprintProposal'),
        ),
        migrations.AddField(
            model_name='sprintcheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sprintcheckin',
            unique_together=set([('user', 'sprint')]),
        ),
    ]
