# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0016_auto_20170701_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtime',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyconkr.ProgramDate'),
        ),
    ]
