# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0017_programtime_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_breaktime',
            field=models.BooleanField(default=True),
        ),
    ]
