# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0018_program_is_breaktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='is_breaktime',
            field=models.BooleanField(default=False),
        ),
    ]
